[package]
name = "maniro-liro/bmf"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
observers = "sleitnick/observers@0.5.0"
shake = "sleitnick/shake@1.1.0"
trove = "sleitnick/trove@1.8.0"
spring = "sleitnick/spring@1.0.0"
signal = "sleitnick/signal@2.0.3"
table-util = "sleitnick/table-util@1.2.1"
topbarplus = "1foreverhd/topbarplus@3.4.0"
t = "osyrisrblx/t@3.1.1"

[server-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"